# Generated by Django 2.2.14 on 2020-07-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=30, verbose_name='サンプル名')),
                ('rock_type', models.CharField(max_length=20, verbose_name='岩石名')),
                ('weight', models.IntegerField(verbose_name='重さ[キログラム]')),
                ('sampling_date', models.DateField(verbose_name='採集年月日')),
            ],
        ),
    ]
