# Generated by Django 2.2.14 on 2020-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='owner',
            field=models.CharField(default='苗村', max_length=10, verbose_name='保管者'),
        ),
        migrations.AddField(
            model_name='top',
            name='project',
            field=models.CharField(default='チェコ研究', max_length=30, verbose_name='プロジェクト'),
        ),
        migrations.AddField(
            model_name='top',
            name='terrane',
            field=models.CharField(default='Moldanubia', max_length=20, verbose_name='テレーン'),
        ),
        migrations.AlterField(
            model_name='top',
            name='weight',
            field=models.IntegerField(verbose_name='重さ[グラム]'),
        ),
    ]
