# Generated by Django 2.2.14 on 2020-07-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0002_auto_20200712_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='owner',
            field=models.CharField(default='管理者詳細', max_length=10, verbose_name='保管者'),
        ),
        migrations.AlterField(
            model_name='top',
            name='project',
            field=models.CharField(default='プロジェクト詳細', max_length=30, verbose_name='プロジェクト'),
        ),
        migrations.AlterField(
            model_name='top',
            name='terrane',
            field=models.CharField(default='地域詳細', max_length=20, verbose_name='テレーン'),
        ),
    ]
