# Generated by Django 2.2.13 on 2020-07-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0003_auto_20200712_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='top',
            name='project',
        ),
        migrations.RemoveField(
            model_name='top',
            name='terrane',
        ),
    ]
