# Generated by Django 2.2.4 on 2020-06-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '所有者',
                'verbose_name_plural': '所有者',
                'db_table': 'Owner',
            },
        ),
    ]
