# Generated by Django 2.2.14 on 2020-07-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toppage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, verbose_name='産地国')),
                ('terrane', models.CharField(max_length=20, verbose_name='テレーン')),
                ('locality', models.CharField(max_length=50, verbose_name='産地詳細')),
                ('lon', models.DecimalField(decimal_places=3, help_text='単位はディグリー', max_digits=8, verbose_name='経度[°]')),
                ('lat', models.DecimalField(decimal_places=3, help_text='単位はディグリー', max_digits=8, verbose_name='緯度[°]')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toppage.Top', verbose_name='サンプルID')),
            ],
        ),
    ]
