# Generated by Django 2.2.14 on 2020-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='EandW',
            field=models.BooleanField(blank=True, null=True, verbose_name='東西'),
        ),
        migrations.AddField(
            model_name='locality',
            name='NandS',
            field=models.BooleanField(blank=True, null=True, verbose_name='南北'),
        ),
    ]
