# Generated by Django 2.2.14 on 2020-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0003_auto_20200711_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='terrane',
            field=models.CharField(default='Moldanubia', max_length=20, verbose_name='テレーン'),
        ),
    ]
