# Generated by Django 2.2.14 on 2020-07-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0004_auto_20200712_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='terrane',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='テレーン'),
        ),
    ]
