# Generated by Django 2.2.13 on 2020-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0006_auto_20200730_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='photo',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
