# Generated by Django 2.2.13 on 2020-07-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0008_auto_20200730_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='photo',
            field=models.ImageField(default='defo', upload_to='image/'),
        ),
    ]
