# Generated by Django 2.2.14 on 2020-07-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toppage', '0003_auto_20200712_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='採集者')),
                ('storage', models.CharField(max_length=20, verbose_name='保管場所')),
                ('box_number', models.IntegerField(verbose_name='保管箱番号')),
                ('thin_section', models.BooleanField(blank=True, null=True, verbose_name='薄片の有無')),
                ('thin_section_box', models.CharField(max_length=20, verbose_name='薄片箱名')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toppage.Top', verbose_name='サンプルID')),
            ],
        ),
    ]
