# Generated by Django 2.2.14 on 2020-07-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toppage', '0003_auto_20200712_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(verbose_name='タイプ')),
                ('project', models.CharField(max_length=30, verbose_name='プロジェクト名')),
                ('funding', models.CharField(max_length=20, verbose_name='研究費')),
                ('publication', models.CharField(max_length=50, verbose_name='関連論文')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toppage.Top', verbose_name='サンプルID')),
            ],
        ),
    ]
