# Generated by Django 2.2.14 on 2020-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='type',
            field=models.BooleanField(verbose_name='研究'),
        ),
    ]
